import { Akaya_Kanadaka, Josefin_Sans } from "next/font/google";
import "./globals.css";

const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-josefin-sans",
  weight: ["400"],
});

const akayaKanadaka = Akaya_Kanadaka({
  subsets: ["latin"],
  variable: "--font-akaya-kanadaka",
  weight: ["400"],
});

export const metadata = {
  title: "Narendra ♡ Aarthi - 1 Feb, 2024",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${josefinSans.variable} ${akayaKanadaka.variable}`}>
        {children}
      </body>
    </html>
  );
}
